### ISSUE TITLE
sqlite3 to postgres problems

### ISSUE THREAD

**Issue by ghost** [ricardochimal/taps#15]
I was moving a database from sqlite3 to postgres, and thought I would describe the problems.

varchar(255) columns - in sqlite3 these can hold strings longer than 255, but not in postgres
varchar/text columns - in sqlite3 these can hold bytes with values > 127, and I couldn't figure out how to enable whatever translation was needed, I ended up patching the sqlite3 gem to convert them all to utf-8 before returning them to sequel.
timestamp columns - There were a bunch of records with null timestamps.  These I updated until they were all valid timestamps.

**Comment by ricardochimal** [comment]
The problem is that sqlite3 doesn't actually enforce any limits, varchar(255) means that it can only hold characters up to 255 chars in length, sqlite doesn't actually pay attention to this but postgres does.  The same thing happens with your bytes w/ values > 127 problem, postgres will enforce character encodings but sqlite will not.  

http://www.sqlite.org/faq.html#q3
